//
//  Lang.swift
//  Tweetarium
//
//  Created by Ahmed Fathy on 28/12/2022.
//

import Foundation

enum TwitterLang: String, Codable {
    case Amharic = "am"
    case Arabic = "ar"
    case German = "de"
    case Greek = "el"
    case Malayalam = "ml"
    case Maldivian = "dv"
    case Slovak = "sk"
    case Slovenian = "sl"
    case Basque = "eu"
    case Bengali = "bn"
    case Bosnian = "bs"
    case Bulgarian = "bg"
    case Burmese = "my"
    case Croatian = "hr"
    case Catalan = "ca"
    case Czech = "cs"
    case HaitianCreole = "ht"
    case Hebrew = "iw"
    case Hindi = "hi"
    case LatinizedHindi = "hi-Latn"
    case Hungarian = "hu"
    case Icelandic = "is"
    case Indonesian = "in"
    case Italian = "it"
    case Nepali = "ne"
    case Norwegian = "no"
    case Oriya = "or"
    case Pashto = "ps"
    case Persian = "fa"
    case Polish = "pl"
    case Portuguese = "pt"
    case Spanish = "es"
    case Swedish = "sv"
    case Tagalog = "tl"
    case Panjabi = "pa"
    case Telugu = "te"
    case Thai = "th"
    case Tibetan = "bo"
    case TraditionalChinese = "zh-TW"
    case Tamil = "ta"
    case Danish = "da"
    case Dutch = "nl"
    case English = "en"
    case Estonian = "et"
    case Finnish = "fi"
    case French = "fr"
    case Georgian = "ka"
    case Japanese = "ja"
    case Kannada = "kn"
    case Korean = "ko"
    case Khmer = "km"
    case Lao = "lo"
    case Latvian = "lv"
    case Lithuanian = "lt"
    case Romanian = "ro"
    case Russian = "ru"
    case Serbian = "sr"
    case SimplifiedChinese = "zh-CN"
    case Sindhi = "sd"
    case Sinhala = "si"
    case Turkish = "tr"
    case Ukrainian = "uk"
    case Urdu = "ur"
    case Vietnamese = "vi"
    case Welsh = "cy"
    case Uyghur = "ug"
    case undefined = "und"
}
